version: "3.1"
services:
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                     C O D E I G N I T E R  v4.2.3                        #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
    codeigniter4:
        image: atsanna/codeigniter4:alpine
#        image: atsanna/codeigniter4:v4.2.3-php8.1-apache
#        image: atsanna/codeigniter4:v4.2.3-php8.1.9-apache
#        image: atsanna/codeigniter4:v4.2.3-php8.0-apache
#        image: atsanna/codeigniter4:v4.2.3-php8.0.20-apache
#        image: atsanna/codeigniter4:v4.2.3-php7.4-apache
#        image: atsanna/codeigniter4:v4.2.3-php7.4.30-apache
#        container_name: 'codeigniter4'
        environment:
          - REGEN_ENV_FILE=1

          - CI_ENVIRONMENT=development
          - APP_BASE_URL=http://localhost/
          - DB_DEFAULT_HOSTNAME=localhost:3306
          - DB_DEFAULT_DATABASE=app
          - DB_DEFAULT_USERNAME=root
          - DB_DEFAULT_PASSWORD=test
          - DB_DEFAULT_DRIVER=MySQLi
          - DB_DEFAULT_PORT=3306

        ports:
          - 80:80
        links:
          - db
        volumes:
          - ./www:/var/www/html
    db:
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: app
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
            UPLOAD_LIMIT: 300M 
volumes:
    persistent:
